language: node_js
node_js: 8.0
deploy:
  provider: pages
  local_dir: dest
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: tituswormer@gmail.com
  name: Titus Wormer
  on:
    branch: src
